---
version: edm_1_0

description: |
  The quick brown fox jumps over the lazy dog.

metadata:
  maintainer: Michael Wurster <miwurster@gmail.com>

imports:
  - types.yml

properties:
  aws_access_key:
    type: string
  aws_secret_access_key:
    type: string

components:

  ec2:
    type: service_cloud_aws_ec2
    properties:
      aws_access_key: ${GLOBAL.aws_access_key}
      aws_secret_access_key: ${GLOBAL.aws_secret_access_key}
      aws_region: eu-west-1
      vpc_security_group: default
      subnet: default

  ubuntu:
    type: compute_cloud
    properties:
      machine_image: ami-00035f41c82244dab
      instance_type: t2.micro
      key_name: test
      public_key: ${GLOBAL.public_key}
    operations:
      configure: ubuntu/configure.sh
    relations:
      - hosted_on: ec2

  tomcat:
    type: tomcat
    relations:
      - hosted_on: ubuntu

  app:
    type: software_component
    operations:
      create: app/install.sh
    artifacts:
      - war: app/app.war
    relations:
      - hosted_on: tomcat
      - connects_to: queue

  queue:
    type: service_cloud_aws_sqs
    properties:
      queue_name: orders
      aws_access_key: ${GLOBAL.aws_access_key}
      aws_secret_access_key: ${GLOBAL.aws_secret_access_key}
      aws_region: eu-west-1

  worker:
    type: service_cloud_aws_lambda
    properties:
      timeout: 5
      aws_access_key: ${GLOBAL.aws_access_key}
      aws_secret_access_key: ${GLOBAL.aws_secret_access_key}
      aws_region: eu-west-1
    artifacts:
      - nodejs: worker/index.js
    relations:
      - subscribes_to: queue
